name: CI

on:
  push

jobs:
  lint:
    name: StyleCop Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        id: restore
        run: |
          solution=$(find . -name "*.sln" | head -n 1)
          if [ -z "$solution" ]; then
            project=$(find . -name "*.csproj" | head -n 1)
            echo "path=$project" >> $GITHUB_OUTPUT
            dotnet restore "$project"
          else
            echo "path=$solution" >> $GITHUB_OUTPUT
            dotnet restore "$solution"
          fi

      - name: Build with StyleCop
        run: dotnet build ${{ steps.restore.outputs.path }} --no-restore --configuration Release -warnaserror

      - name: Upload lint log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: stylecop-log
          path: '**/*.binlog'

  build:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-script: ./build-and-test.sh
          - os: macos-latest
            build-script: ./build-and-test.sh
          - os: windows-latest
            build-script: ./build-and-test.ps1

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Make script executable
        if: runner.os != 'Windows'
        run: chmod +x build-and-test.sh

      - name: Build
        run: ${{ matrix.build-script }} build

      - name: Test
        run: ${{ matrix.build-script }} test
